name: CI/CD Pipeline

# This workflow runs on pushes and pull requests to the 'main' branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    # Use the latest version of Ubuntu as the runner
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out your repository code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up the Python version to match your project
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.3' # Ensure this matches your project's version

    # Step 3: Install all the Python dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .

    # Step 4: Run your tests using pytest
    - name: Run tests with pytest
      run: |
        pytest

    # Step 5: Log in to Docker Hub
    # This uses secrets to securely log in without exposing your password
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    # Step 6: Build and push the Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/student-performance-app:latest
